before_script:
  - uname -a
  - hostname
  - pwd
  - echo $USER
  - echo $HOME
  - rm -rf ./tasks
  - git clone git@gitlab.com:iqs-management/iqs-devops-buildtasks.git tasks

stages:
  - build
  - stage-deploy
  - prod-deploy

build:
  stage: build
  script:
  - echo "Build the app"
  - ./tasks/increment.sh
  - ./build.sh
  - ./test.sh
  - ./package.sh
  #- ./tag.sh
  #- ./release.sh
  #- ./publish.sh
  after_script:
  #- ./clean.sh  
  artifacts:
    paths:
    - component.json
  
stage_deploy:
  stage: stage-deploy
  script:
  - echo "Deploy into staging environment"
  #- ./tasks/deploy.sh
  #- ./tasks/validate.sh
  #- ./tasks/promote.sh
  after_script:
  #- ./tasks/rollback.sh
  #- ./clean.sh  
  variables:
    ENVIRONMENT: stage
  environment:
    name: stage
    url: https://staging.example.com
  dependencies:
  - build
  only:
  - master

prod_deploy:
  stage: prod-deploy
  script:
  - echo "Deploy into production environment"
  #- ./tasks/deploy.sh
  #- ./tasks/validate.sh
  after_script:
  #- ./tasks/rollback.sh
  #- ./clean.sh  
  variables:
    ENVIRONMENT: prod
  environment:
    name: stage
    url: https://prod.example.com
  dependencies:
  - build
  when: manual
  only:
  - master
