language: node_js
sudo: true
node_js:
  - "node"

services:
  - mongodb

env:
  DOCKER_USER=krdmitriy

before_install:
  - ./build.sh

install:
  - ./test.sh
  - ./package.sh
  - ./publish.sh

script: echo "npm test temporarily disabled"

after_success:
  - sed -i -e 's/BUILD_NUMBER=[0-9]*-rc/BUILD_NUMBER=${TRAVIS_BUILD_NUMBER }-rc/g' ./deploy_scripts/upgrade-stage.sh
  - git add ./deploy_scripts/upgrade-stage.sh
  - git commit -m "updated build version"
  - git push origin master

after_script:
  - ./clean.sh