language: node_js
sudo: true
node_js:
  - "node"

services:
  - mongodb

env:
  DOCKER_USER=krdmitriy

before_install:
  - ./build.sh

install:
  - ./test.sh
  - ./package.sh
  - ./publish.sh

script: echo "npm test temporarily disabled"

after_success:
  - sed -i -e "s/BUILD_NUMBER=[0-9]*-rc/BUILD_NUMBER=$TRAVIS_BUILD_NUMBER-rc/g" ./deploy_scripts/upgrade-stage.sh
  - git config --global user.email "krdima92@gmail.com" 
  - git config --global user.name "stee1" 
  - git add ./deploy_scripts/upgrade-stage.sh
  - git remote -v
#  - git remote rm origin 
#  - git remote add origin "https://stee1:$GITHUB_API_KEY@github.com/pip-services-content/pip-services-dashboards-node.git"
  - git commit -m "Travis build $TRAVIS_BUILD_NUMBER updated build number in stage deploy file [skip ci]" 
  - git push origin master

after_script:
  - ./clean.sh