language: node_js
sudo: true
node_js:
  - "node"

services:
  - mongodb

branches:
  except:
    - /^v[0-9]/

if: tag IS blank

env:
  DOCKER_USER=krdmitriy
  NPM_USER=pipdeveloper
  NPM_EMAIL=pipdevs@gmail.com
  REGISTRY=pipdevs

before_install:
  - echo "Installing powershell..."
  - curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
  - curl https://packages.microsoft.com/config/ubuntu/16.04/prod.list | sudo tee /etc/apt/sources.list.d/microsoft.list
  - sudo apt-get update
  - wget http://security.ubuntu.com/ubuntu/pool/main/i/icu/libicu55_55.1-7ubuntu0.4_amd64.deb
  - sudo apt-get install build-essential
  - sudo apt-get install aptitude
  - sudo apt-get install libstdc++6
  - sudo apt install ./libicu55_55.1-7ubuntu0.4_amd64.deb
  - sudo apt-get install -y powershell
  - echo "Powershell installed"
  - ./build.ps1

install:
  - ./test.ps1
  - ./package.ps1
  - ./publish.ps1

script: 
  echo "npm test temporarily disabled"

after_success:
  - ./tag.ps1
  - ./release.ps1

after_script:
  - ./clean.ps1