language: node_js
sudo: true
node_js:
  - "node"

services:
  - mongodb

branches:
  except:
    - /^v[0-9]/

if: tag IS blank

env:
  DOCKER_USER=krdmitriy
  NPM_USER=pipdeveloper
  NPM_EMAIL=pipdevs@gmail.com
  REGISTRY=pipdevs

before_install:
  - uname -a
  - curl -SL https://github.com/PowerShell/PowerShell/releases/download/v6.0.0-alpha.9/powershell_6.0.0-alpha.9-1ubuntu1.14.04.1_amd64.deb -o powershell_6.0.0-alpha.9-1ubuntu1.14.04.1_amd64.deb
  - sudo apt-get install libunwind8 libicu52
  - sudo dpkg -i powershell_6.0.0-alpha.9-1ubuntu1.14.04.1_amd64.deb
  - ./build.ps1

install:
  - ./test.sh
  - ./package.sh
  - ./publish.sh

script: 
  echo "npm test temporarily disabled"

after_success:
  - ./tag.sh
  - ./release.sh

after_script:
  - ./clean.sh