---
- descriptor: "pip-services-commons:logger:console:default:1.0"
  level: "trace"

- descriptor: "pip-services-dashboards:persistence:file:default:1.0"
  path: "./data/dashboards.json"

- descriptor: "pip-services-dashboards:controller:default:default:1.0"

- descriptor: "pip-services-dashboards:service:http:default:1.0"
  connection:
    protocol: "http"
    host: "0.0.0.0"
    port: 8080
